a = input('Dígite algo ')
print('O tipo priitivo desse valor é {}'.format(type(a)))
print('Só tem espaços {}'.format(a.isspace()))
print('É número {}'.format(a.isnumeric()))
print('É alfabetico {}'.format(a.isalpha()))
print('É alfanumérico {}'.format(a.isalnum()))
print('É maiusculo {}'.format(a.isupper()))
print('É minusculo {}'.format(a.islower()))
print('É capitalizado {}'.format(a.istitle()))
