tab = int(input('Dígite o número da tabuada '))
print('==============')
print('{} X 1 = {}'.format(tab, tab*1))
print('{} X 2 = {}'.format(tab, tab*2))
print('{} X 3 = {}'.format(tab, tab*3))
print('{} X 4 = {}'.format(tab, tab*4))
print('{} X 5 = {}'.format(tab, tab*5))
print('{} X 6 = {}'.format(tab, tab*6))
print('{} X 7 = {}'.format(tab, tab*7))
print('{} X 8 = {}'.format(tab, tab*8))
print('{} X 9 = {}'.format(tab, tab*9))
print('{} X 10 = {}'.format(tab, tab*10))
print('===============')
